# Generated by Django 2.2 on 2019-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_doctor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(default='Doctot'),
            preserve_default=False,
        ),
    ]
